# Generated by Django 4.1.7 on 2023-02-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='productName',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productP',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productQ',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
